name: Publish NuGet Packages

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x

      - name: Publish NuGet package
        id: publish
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/NekoSpace.Build.Resources.Json/NekoSpace.Build.Resources.Json.csproj
          PACKAGE_NAME: NekoSpace.Build.Resources.Json
          VERSION_FILE_PATH: src/NekoSpace.Build.Resources.Json/NekoSpace.Build.Resources.Json.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}